# Generated by Django 5.2.17 on 2026-09-23 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alias",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("fmcg", "FMCG / Grocery"),
                            ("pharma", "Pharma"),
                            ("hardware", "Hardware"),
                            ("electronics", "Electronics"),
                            ("food_grain", "Rice / Food grain"),
                            ("other", "Other"),
                        ],
                        default="fmcg",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=16)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("trade_licence", models.CharField(blank=True, max_length=60)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "default_credit_limit",
                    models.DecimalField(decimal_places=2, default=50000, max_digits=12),
                ),
                ("default_due_days", models.PositiveSmallIntegerField(default=15)),
                (
                    "require_owner_approval_over_limit",
                    models.BooleanField(default=True),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("rep", "Sales rep"),
                            ("accountant", "Accountant"),
                        ],
                        default="rep",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="businesses.business",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "user"), name="unique_member"
                    )
                ],
            },
        ),
    ]
