# Generated by Django 5.2.17 on 2026-09-23 17:17

import apps.shops.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('assigned_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_areas', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='businesses.business')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12)),
                ('due_days', models.PositiveSmallIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('last_payment_at', models.DateField(blank=True, null=True)),
                ('due_since', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.area')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='ShopShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.shops.models._token, max_length=32, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_payment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_area_name'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['business', 'area'], name='shops_shop_busines_2b0369_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['business', 'current_balance'], name='shops_shop_busines_4c4868_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['business', 'due_since'], name='shops_shop_busines_03f04f_idx'),
        ),
    ]
