# Generated by Django 5.2.17 on 2026-09-23 09:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("object_type", models.CharField(max_length=40)),
                ("object_id", models.CharField(max_length=40)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="businesses.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "created_at"],
                        name="ledger_audi_busines_3fee0d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("sale", "Sale on credit"),
                            ("payment", "Payment"),
                            ("return", "Return"),
                            ("discount", "Discount"),
                            ("write_off", "Write-off"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("direction", models.SmallIntegerField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("entry_date", models.DateField()),
                ("memo_no", models.CharField(blank=True, max_length=40)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("cash", "Cash"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank", "Bank transfer"),
                            ("cheque", "Cheque"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="memos/")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("voice", "Voice (AI)"),
                            ("ocr", "Photo (AI)"),
                            ("online", "Online payment"),
                            ("import", "Import"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.ledgerentry",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["entry_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["business", "shop", "entry_date"],
                        name="ledger_ledg_busines_b42ba0_idx",
                    ),
                    models.Index(
                        fields=["business", "entry_date"],
                        name="ledger_ledg_busines_12af1d_idx",
                    ),
                    models.Index(
                        fields=["business", "created_by", "entry_date"],
                        name="ledger_ledg_busines_d13b07_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("business", "idempotency_key"),
                        name="unique_idempotency_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="entry_amount_positive",
                    ),
                ],
            },
        ),
    ]
