# Generated by Django 5.2.17 on 2026-09-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('days_before_due', models.PositiveSmallIntegerField(default=3)),
                ('remind_on_overdue', models.BooleanField(default=True)),
                ('repeat_every_days', models.PositiveSmallIntegerField(default=7)),
                ('send_receipts', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rule', to='businesses.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16)),
                ('kind', models.CharField(choices=[('reminder', 'Reminder'), ('overdue', 'Overdue notice'), ('receipt', 'Payment receipt'), ('custom', 'Custom')], default='custom', max_length=10)),
                ('body', models.TextField()),
                ('parts', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=8)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=80)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='businesses.business')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='notificatio_busines_02e103_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('reminder', 'Reminder'), ('overdue', 'Overdue notice'), ('receipt', 'Payment receipt'), ('custom', 'Custom')], max_length=10)),
                ('body', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='businesses.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'kind'), name='one_template_per_kind')],
            },
        ),
    ]
